name: Build and Push ECR Image

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      ecr-repo:
        required: true
        type: string
      github-role-arn:
        required: true
        type: string
      image-tag:
        required: true
        type: string

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.github-role-arn }}

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build image
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: |
          docker build --build-arg REVISION=${{ inputs.image-tag }} -t $ECR_REGISTRY/${{ inputs.ecr-repo-name }}:${{ inputs.image-tag }} .

      - name: Push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/${{ inputs.ecr-repo-name }}:${{ inputs.image-tag }}

          echo "image-url=$ECR_REGISTRY/${{ inputs.ecr-repo }}:${{ inputs.image-tag }}" >> $GITHUB_OUTPUT
